import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Greeting Next.js</title>
        <link href="/fontawesome/css/fontawesome.css" rel="stylesheet" />
        <link href="/fontawesome/css/brands.css" rel="stylesheet" />
        <link href="/fontawesome/css/regular.css" rel="stylesheet" />
        <link href="/fontawesome/css/solid.css" rel="stylesheet" />
      </head>
      <body
        className={"font-open-sans min-h-screen bg-stone-100"}
        suppressHydrationWarning
      >
        <div className={"container mx-auto flex min-h-screen flex-col gap-y-4"}>
          <label>
            Name
            <input />
          </label>
          <main className={"flex-grow flex-col bg-white px-8 py-4"}>
            {children}
          </main>
          {/*<ReactQueryDevtools />*/}
        </div>
      </body>
    </html>
  );
}
